apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - prometheus-install/prometheus/application.yaml
  - prometheus-install/prometheus-operator-crds/application.yaml
  - promethesu-install/prometheus-node-exporter/application.yaml
  - promethesu-install/grafana/dashboard/arogcd.yaml